// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TUr0OAiYEg1acT-6scIiQFv7c8VT4T4',
    appId: '1:834220192091:web:11e0098e7b85211d8a2a7e',
    messagingSenderId: '834220192091',
    projectId: 'skycast-45afc',
    authDomain: 'skycast-45afc.firebaseapp.com',
    storageBucket: 'skycast-45afc.firebasestorage.app',
    measurementId: 'G-F04DSVB24E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ErmrNrd8WV4TA5_phzmG7fH_jLmRB28',
    appId: '1:834220192091:android:f7c0da99c25b50be8a2a7e',
    messagingSenderId: '834220192091',
    projectId: 'skycast-45afc',
    storageBucket: 'skycast-45afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpvjfWZUwAGyMTo0TFUqO1B6_QOEbUqA',
    appId: '1:834220192091:ios:11e294335dd24da68a2a7e',
    messagingSenderId: '834220192091',
    projectId: 'skycast-45afc',
    storageBucket: 'skycast-45afc.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );
}
